language: python
env:
  - DJANGO_VERSION="Django>=1.8,<1.9" DJANGO_SETTINGS_MODULE=
  - DJANGO_VERSION="Django>=1.9,<1.10" DJANGO_SETTINGS_MODULE=
  - DJANGO_VERSION="Django>=1.10,<1.11" DJANGO_SETTINGS_MODULE=
  - DJANGO_VERSION="Django>=1.11,<2" DJANGO_SETTINGS_MODULE=
python:
  - "2.7"
  - "3.4"
  - "3.5"
before_install:
  - export BOTO_CONFIG=/dev/null
# command to install dependencies
install:
  - pip install -q $DJANGO_VERSION
  - pip install -q -r requirements.txt
  - pip install -q -e .
# command to run tests
script: make test
after_success:
  - coveralls
