language: python
env:
  - DJANGO_VERSION="Django>=1.6,<1.7" DJANGO_SETTINGS_MODULE=
  - DJANGO_VERSION="Django>=1.7,<1.8" DJANGO_SETTINGS_MODULE=
  - DJANGO_VERSION="Django>=1.8,<1.9" DJANGO_SETTINGS_MODULE=
  - DJANGO_VERSION="Django>=1.9,<1.10" DJANGO_SETTINGS_MODULE=
python:
  - "2.7"
  - "3.3"
  - "3.4"
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION="Django>=1.9,<1.10" DJANGO_SETTINGS_MODULE=
# command to install dependencies
install:
  - pip install -q $DJANGO_VERSION
  - pip install -q -r requirements.txt
  - pip install -q -e .
# command to run tests
script: make test
after_success:
  - coveralls
