version: '2.1'
volumes:
  user_uploads:
  wooey_db:

services:
  common:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        BUILD_DIR:
    image: wooey:dev
    volumes :
      - ./user_settings.py:/docker_wooey/docker_wooey/settings/user_settings.py
      - user_uploads:/docker_wooey/docker_wooey/user_uploads
    environment:
      AMQP_URL: amqp://rabbit:5672
      BUILD_DIR:
      DATABASE_NAME: wooey
      DATABASE_USER: wooey
      DATABASE_URL: db
      DATABASE_PASSWORD: wooey
      DJANGO_SETTINGS_MODULE: docker_wooey.settings
    user: 1000:1000
